name: blog

on:
  push:
    paths:
      - 'blog/**'
      - '.github/workflows/blog.yml'
  pull_request:
    paths:
      - 'blog/**'
      - '.github/workflows/blog.yml'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: download
      uses: dawidd6/action-download-artifact@v19
      with:
        workflow: build.yml
        name: cblog
        branch: main
        workflow_conclusion: success
        path: ./bin
    - name: set-executable
      run: chmod +x bin/cblog
    - name: run
      run: |-
        while IFS= read -r -d '' f; do
          cat "$f" | ./bin/cblog
        done <<<"$(find 'blog' -type f -print0)"